name: Build AutoFight jar

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.1.1
      - name: Build
        working-directory: autofight
        run: gradle build --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: autofight-jar
          path: autofight/build/libs/autofight-*.jar
